### ISSUE TITLE
Header names MUST be case-insensitive

### ISSUE THREAD

**Issue by WinterSilence** [sunrise-php/http-message#8]
https://github.com/sunrise-php/http-message/blob/739fdd48f0b2f91a1629d952e56e0738aec3ac25/src/Message.php#L291

[psr-7](https://www.php-fig.org/psr/psr-7/#case-insensitive-header-field-names):
> Despite that headers may be retrieved case-insensitively, the original case MUST be preserved by the implementation, in particular when retrieved with getHeaders()

It's based on [rfc7230](https://tools.ietf.org/html/rfc7230#section-3.2):
>  Each header field consists of a case-insensitive field name

**Comment by fenric** [comment]
Hello!

It's RFC-7230 (case-insensitive):

```php
$message = $message->withHeader('X-foo-BAR', 'baz');

$message->hasHeader('x-foo-bar'); // true
$message->hasHeader('x-FoO-bAr'); // true

$message->getHeaderLine('x-foo-bar'); // baz
$message->getHeaderLine('x-FoO-bAr'); // baz
```

Do you want (as PSR-7):

```php
$message->getHeader('x-foo-bar'); // ['X-foo-BAR' => ['baz']]
```

... instead of this (as NOW):

```php
// ['x-foo-bar' => ['baz']]
```

... ? but, why?

**Comment by fenric** [comment]
Do you want to read "AS IS"?

**Comment by WinterSilence** [comment]
@fenric `getHeaders` (and other returned headers with names) must be return headers with names "as is", use `strcasecmp()` insted converting to lower case

**Comment by WinterSilence** [comment]
@fenric as I'm say, it`s `MUST` in psr-7

**Comment by WinterSilence** [comment]
@fenric my english not so good, see [comment to MessageInterface::getHeaders()](https://github.com/php-fig/http-message/blob/master/src/MessageInterface.php#L61)

**Comment by fenric** [comment]
@WinterSilence как и мой, я вернусь к этому вопросу и к `Uri` чуть позже, после маршрутизатора.

**Comment by WinterSilence** [comment]
@fenric я вроде все объяснил - имена заголовков должны возвращаться в том виде в котором их передали, а не нижнем регистре как сейчас, об этом написано в PSR-7, см. описание метода getHeaders

**Comment by fenric** [comment]
#27 v3.0.0
